OyunProjee.WebUI/Models/ViewModels/LoginVM.cs
namespace OyunProjee.WebUI.Models.ViewModels
{
    public class LoginVM
    {
        public string Adı { get; set; }
        public string Soyadı { get; set; }
        public string Logintype { get; set; }
    }
}

OyunProjee.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace OyunProjee.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

OyunProjee.WebUI/Controllers/KarakterController.cs
using Microsoft.AspNetCore.Mvc;
using OyunProjee.Core.Service;
using OyunProjee.Model.Entities;

namespace OyunProjee.WebUI.Controllers
{
    public class KarakterController : Controller
    {
        private readonly IOyunService<Karakter> _k;
        
        public KarakterController(IOyunService<Karakter> k, IOyunService<Oyun> o)
        {
            _k = k;
            
        }

        public IActionResult Listele()
        {

            return View(_k.GetAll());
        }
        public IActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Ekle(Karakter k)
        {
            if (k.OyunAdı != null && k.OyuncuAdı != null && k.Gucu != null && k.Vurus != null && k.FızıkselOzellik != null)
            {
                return _k.Add(k) ? View("Listele", _k.GetAll()) : View();
           }
            ViewBag.KarakterError = "Boş bırakılamaz";
            return View();
        }


        public IActionResult Guncelle(int id)
        {
            return View(_k.GetByID(id));
        }

        [HttpPost]
        public IActionResult Guncelle(Karakter a)
        {
            if (a.OyunAdı != null && a.OyuncuAdı != null && a.Gucu != null && a.Vurus != null && a.FızıkselOzellik != null)
            {
                return _k.Update(a) ? View("Listele", _k.GetAll()) : View();
            }
            ViewBag.KarakterError = "Boş bırakılamaz";
            return View();
        }

        public IActionResult Sil(int id)
        {
            return _k.Delete(id) ? View("Listele", _k.GetAll()) : View();
        }




    }
}

OyunProjee.WebUI/Controllers/OyunController.cs
using Microsoft.AspNetCore.Mvc;
using OyunProjee.Core.Service;
using OyunProjee.Model.Entities;

namespace OyunProjee.WebUI.Controllers
{
    public class OyunController : Controller
    {
        private readonly IOyunService<Oyun> _oyun;
        public OyunController(IOyunService<Oyun> oyun)
        {
            _oyun = oyun;
        }
        public IActionResult Listele()
        {
            return View(_oyun.GetAll());
        }
        public IActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Ekle(Oyun o)
        {
            if (o.OyunAdı != null && o.KurulusTarihi != null && o.Türü != null && o.Fiyat != null)
            {
                return _oyun.Add(o) ? View("Listele",_oyun.GetAll()) : View();
            }
            ViewBag.OyunAddError = "Boş bırakılamaz";
            return View();
        }

        public IActionResult Guncelle(int id)
        {
            return View(_oyun.GetByID(id));
        }

        [HttpPost]
        public IActionResult Guncelle(Oyun o)
        {
            if (o.OyunAdı != null && o.KurulusTarihi != null && o.Türü != null & o.Fiyat != null) {
                return _oyun.Update(o) ? View("Listele", _oyun.GetAll()) : View();
            }
            ViewBag.OyunAddError = "Boş bırakılamaz";
            return View();
        }

        public IActionResult Sil(int id)
        {
            return _oyun.Delete(id) ? View("Listele", _oyun.GetAll()) : View();
        }



    }
}

OyunProjee.WebUI/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace OyunProjee.WebUI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

OyunProjee.WebUI/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OyunProjee.WebUI.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

OyunProjee.WebUI/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OyunProjee.WebUI.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

OyunProjee.WebUI/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OyunProjee.WebUI/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OyunProjee.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OyunProjee.WebUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OyunProjee.WebUI - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OyunProjee.WebUI/Pages/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OyunProjee.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OyunProjee.WebUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OyunProjee.WebUI - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OyunProjee.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Anasayfa</h1>

OyunProjee.WebUI/Views/Karakter/Ekle.cshtml
@model Karakter
@{
    ViewData["Title"] = "Ekle";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Ekle</h1>
@if (ViewBag.KarakterError != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.KarakterAddError
    </div>
}
else
{
    <form asp-controller="Karakter" asp-action="Ekle" method="post">
        <input type="text" name="OyunAdı" placeholder="Oyun Adı Giriniz" /><br /><br />
        <input type="text" name="OyuncuAdı" placeholder="Oyuncu adı giriniz"><br/><br/>
        <input type="text" name="OyuncuOzellikleri" placeholder="Oyuncu Özelliklerini Giriniz"><br/><br/>
        <input type="text" name="Gucu" placeholder="Gücünü Giriniz"><br/><br/>
        <input type="text" name="Vurus" ><br/><br/>
        <input type="text" name="FızıkselOzellik"> 
        <input type="submit" value="Kaydet" class="btn btn-success" />
    </form>
}

OyunProjee.WebUI/Views/Karakter/Guncelle.cshtml
@model Karakter
@{
    ViewData["Title"] = "Guncelle";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Guncelle</h1>
@if (ViewBag.OyunAddError != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.OyunAddError
    </div>
}
else
{
    <form asp-controller="Oyun" asp-action="Guncelle" method="post">
       <input type="number" name="Id" value="@Model.Id">
       <input type="text" name="OyuncuAdı" value="@Model.OyuncuAdı">
       <input type="text" name="OyuncuOzellikleri" value="@Model.OyuncuOzellikleri">
       <input type="text" name="Gucu" value="@Model.Gucu">
       <input type="text" name="Vurus" value="@Model.Vurus">
       <input type="text" name="FızıkselOzellik" value="@Model.FızıkselOzellik">
       <input type="submit" value="Guncelle" class="btn-btn-success">
    </form>
}

OyunProjee.WebUI/Views/Karakter/Listele.cshtml
@model IEnumerable<Karakter>
@{
    ViewData["Title"] = "Listele";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Listele</h1>
@if (Model.Count() == 0)
{
    <div class="alert alert-danger" role="alert">
        Kayıt Bulunamadı..!
    </div>
}
else
{
    <table class="table">
        <thead>
        <th scope="col">Karakterler</th>
            
            </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="table-active">
                    ...
                </tr>
                <tr>
                    ...
                </tr>
                <tr>
                    <th scope="row">@item.Id</th>
                    <td>@item.OyunAdı></td>
                    <td><a asp-controller="Karakter" asp-action="Guncelle" asp-route-id="@item.Id" class="btn btn-outline-success"></a>
                    <td></td>
                </tr>
                <tr>
                    <th scope="row">@item.Id</th>
                    <td>@item.OyuncuAdı></td>
                    <td><a asp-controller="Karakter" asp-action="Guncelle" asp-route-id="@item.Id" class="btn btn-outline-success"></a>
                    <td></td>
                </tr>
                <tr>
                    <th scope="row">@item.Id</th>
                    <td>@item.OyuncuOzellikleri></td>
                    <td><a asp-controller="Karakter" asp-action="Guncelle" asp-route-id="@item.Id" class="btn btn-outline-success"></a>
                    <td></td>
                </tr>
                <tr>
                    <th scope="row">@item.Id</th>
                    <td>@item.Gucu></td>
                    <td><a asp-controller="Karakter" asp-action="Guncelle" asp-route-id="@item.Id" class="btn btn-outline-success"></a>
                    <td></td>
                </tr>
                <tr>
                    <th scope="row">@item.Id</th>
                    <td>@item.Vurus></td>
                    <td><a asp-controller="Karakter" asp-action="Guncelle" asp-route-id="@item.Id" class="btn btn-outline-success"></a>
                    <td></td>
                </tr>
                <tr>
                    <th scope="row">@item.Id</th>
                    <td>@item.FızıkselOzellik></td>
                    <td><a asp-controller="Karakter" asp-action="Guncelle" asp-route-id="@item.Id" class="btn btn-outline-success"></a>
                    <td></td>
                </tr>
                
            }
        </tbody>
    </table>
}

OyunProjee.WebUI/Views/KullanıcıKontroller/Ekle.cshtml
@model Kullanıcı
@{
    ViewData["Title"] = "Ekle";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Ekle</h1>
@if (ViewBag.KullanıcıError != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.KullanıcıAddError
    </div>
}
else
{
    <form asp-controller="Karakter" asp-action="Ekle" method="post">
        <div class="form-group">
            <label>KullanıcıAdı</label>
            <input type="text" name="KullanıcıAdı" placeholder="Kullanıcı Adını Giriniz">
            
        </div>
        <div class="form-group">
            <label>KullanıcıSoyadı</label>
            <input type="text" name="KullanıcıSoyadı" placeholder="Kullanıcı Soyadını Giriniz">

        </div>
        <div class="form-group">
            <label>Şifre</label>
            <input type="password" name="Sifre" placeholder="Password">
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
}

OyunProjee.WebUI/Views/Oyun/Ekle.cshtml
@model Oyun
@{
    ViewData["Title"] = "Ekle";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Ekle</h1>
@if (ViewBag.OyunAddError != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.OyunAddError
    </div>
}

<form asp-controller="Oyun" asp-action="Ekle" method="post">
    <div class="form-group">
        <label for="exampleFormControlInput1">OyunAdı</label>
        <input type="text" name="OyunAdı" placeholder="Oyun adını giriniz" />
        <label for="exampleFormControlInput1">Kuruluş Tarihi</label>
        <input type="text" name="KurulusTarihi" placeholder="Oyun adını giriniz" />
    <div class="form-group"
        <label>Oyunun Türü</label>
        <select class="form-control" name="Türü">
            <option>Futbol</option>
            <option>Basketbol</option>
            <option>Strateji</option>
            <option>Araba</option>
            <option>Silah</option>
        </select>
    </div>
    <input type="number" name="Fiyat" />
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Example textarea</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
</form>

OyunProjee.WebUI/Views/Oyun/Guncelle.cshtml
@model Oyun
@{
    ViewData["Title"] = "Guncelle";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Guncelle</h1>
@if (ViewBag.OyunAddError != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.OyunAddError
    </div>
}
else {
    <form asp-controller="Oyun" asp-action="Guncelle" method="post">
    <div class="form-group">
        <input type="text" name="Id" value="@Model.Id">
        <label for="exampleFormControlInput1">OyunAdı</label>
        <input type="text" name="OyunAdı" placeholder="Oyun adını giriniz"  value="@Model.OyunAdı">
        <label for="exampleFormControlInput1">Kuruluş Tarihi</label>
        <input type="text" name="KurulusTarihi" placeholder="Oyun adını giriniz" value="@Model.KurulusTarihi">
    <div class="form-group">
        <label>Oyunun Türü</label>
        <select class="form-control" name="Türü" value="@Model.Türü">
           <option>Futbol</option>
            <option>Basketbol</option>
            <option>Strateji</option>
            <option>Araba</option>
            <option>Silah</option>
        </select>
    </div>
    <input type="number" name="Fiyat" value="@Model.Fiyat">
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Example textarea</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
    </form>
}

OyunProjee.WebUI/Views/Oyun/Listele.cshtml
@model IEnumerable<Oyun>
@{
    ViewData["Title"] = "Listele";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Oyunları Listele</h1>
@if (Model.Count() == 0)
{
    <div class="alert alert-danger" role="alert">
        Kayıt Bulunamadı..!
    </div>
}
else
{
    <table class="table">
        <thead>
           <th scope="col">Oyun Adı
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="table-active">
                    ...
                </tr>
                <tr>
                    ...
                </tr>
                <tr>
                    <th scope="row">@item.Id</th>
                    <td>@item.OyunAdı></td>
                    <td ><a asp-controller="Oyun" asp-action="Guncelle" asp-route-id="@item.Id" class="btn btn-outline-success"></a>
                    <td></td>
                </tr>
            }
        </tbody>
    </table>
}